# Generated by Django 4.2 on 2023-04-09 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
