# Generated by Django 4.2 on 2023-04-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0002_request_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
